export enum GameSteps {
    DRAW_CARDS = 0,
    BOSS_ASSIGN_AND_SELECT_CARDS = 1,
    SELECT_CARD = 2,
    SELECT_PLAYER_MEMBER = 3,
    SELECT_ENEMY_MEMBER = 4,
    START_TURN = 5,
    DISCARD_REMAINING_CARDS = 6,
    EXECUTE_TURN_ACTIONS = 7,
    CHECK_END_GAME_CONDITION = 8,
    LOOP_BACK = 9
}