export enum GameSteps {
    DRAW_CARDS = 0,
    SELECT_CARD = 1,
    SELECT_PLAYER_MEMBER = 2,
    SELECT_ENEMY_MEMBER = 3,
    START_TURN = 4,
    DISCARD_REMAINING_CARDS = 5,
    EXECUTE_TURN_ACTIONS = 6,
    CHECK_END_GAME_CONDITION = 7,
    LOOP_BACK = 8
}